version: 1
builder:
  configs:
    - documentation_targets:
        - CosmoSQLCore
        - CosmoMSSQL
        - CosmoPostgres
        - CosmoMySQL
        - CosmoSQLite
      swift_version: "6.0"
      platform: macosSpm
