version: 1
swift_versions:
  - 5.10
  - 6.0
platforms:
  - macos-spm
  - ios
  - tvos
  - watchos
  - linux
  - visionos
  - android
builder:
  configs:
    - platform: macos-spm
      documentation_targets:
        - CosmoSQLCore
        - CosmoMSSQL
        - CosmoPostgres
        - CosmoMySQL
        - CosmoSQLite
